### ISSUE TITLE
Suggestion: leave verse numbers in

### ISSUE THREAD

**Issue by embed-net** [jesusbible/jesusbible.github.io#37]
Just a suggestion: leave the verse numbers in so that it's easier to use with Bible software and commentaries that are keyed to verses.

**Comment by jesusbible** [comment]
readme updated to inform users how to enable and disable chapter and verse numbers

**Comment by jesusbible** [comment]
(tap anywhere on the page to view chapter numbers. again to also view verse numbers, and again to disable both. it acts as a 3-way toggle, except for psalms, because psalm numbers are always visible. in that case, tapping/clicking enables/disables verse numbers as a 2-way toggle. you can tap or click anywhere on the page.)
