### ISSUE TITLE
Suggestion:  use a USFM to HTML converter

### ISSUE THREAD

**Issue by embed-net** [jesusbible/jesusbible.github.io#39]
If you stay with USFM through the seds and use a USFM to HTML converter you could probably keep/add footnotes easily e.g.
https://github.com/mondele/usfm2html/tree/master
https://github.com/Bible-Translation-Tools/USFM-Converter
https://github.com/WycliffeAssociates/quick_usfm_converter

and it's probably easy to go from USFM to sword/e-sword/OSIS 
https://github.com/JohnAustinDev/osis-converters
https://github.com/adyeths/u2o

so that your work could be used by others who use bible reading software.

**Comment by jesusbible** [comment]
i could display footnotes easily but i don't want them. see README.md note 17. they're distracting.

the USFM to HTML conversion process i made for this is cleaner than other software: i took special care to manage whitespace so that adding chapter and verse numbers is seamless and flawless.

but i don't fully convert footnotes into html. the usfm is converted enough to ignore footnotes, but not to add them in optionally, like via css. **so that is something i could improve: there are hidden leftover usfm markers in the html that have not been converted to html.**

USFM is exported in the usfm folder. it is intended to be converted into modules for use in sword/e-sword/OSIS/etc. i just haven't gotten around to doing the conversion and releasing modules because there's no ARMv8 compatible software to do that, and i don't need those kinds of modules because i don't use e-sword software, etc. but the files are there and ready, with footnotes.





more about whynot footnotes:

i want to be free of distractions and free other people from such distractions. every single letter of scripture could have a footnote long enough to fill a book. it's arbitrary when people add footnotes. when reading the text, i really believe it gets in the way. for detail oriented study of a verse, i recommend reading the hebrew or greek, and using tools to help with that.

for that i use blueletterbible.org

if you want a version with a few footnotes or a lot of footnotes, then practically any other version will do. the fact that footnotes have become the norm is unfortunate. but a footnote is an interruption. at best, it's a cheap way out of difficult translation problem. at worst, it's an outright  blatant interruption, disrespectful of the speaker, who may be yahweh or yahushua depending on what passage it is.

a major aspect of this project is to keep scripture clean and readable, like the way it was written, and not have yet another reference book. i want scripture to be presented like the flowing text that it is, from one word to the next. it's already quite a concession to add spaces between words, punctuation, paragraph indentation, and all these elements not original to the text - but in the interest of comprehension (providing a text that is presented in the manner we were taught how to read books) i believe these devices are warranted. enjoyable books don't have footnotes. footnotes are like a 3rd party commentary that pulls the reader out of the story. 

for print, i would definitely not allow footnotes. for this website, i don't want them because then i would have to add some sort of button to turn them on and off, and then that button/option itself is a distraction.

i refused to allow chapter and verse numbers for a while, because they're honestly a corruption to the text. but i found myself relying on other software so i could find a verse number. now that i can enable chapter and verse numbers, i really don't need anything else. and i don't miss footnotes.

**Comment by jesusbible** [comment]
to clarify:
i do stay with USFM through the sed edits. the usfm has the footnotes.

there are many formats. is there a format you want, specifically?

**Comment by embed-net** [comment]
Sorry - I must have missed that in your seds.

I broke your setup.sh into a set of sed files that should be identical function to  the monolitic one so you can easily look at extracting the seds from bash to have multiple sed files that are easier to organize and document.

I can use your seds on *your* Bible, but I use at least 3 very different bibles myself, and want the changes you're doing with the seds as commentary lines (for which I require line numbers). Then I can use a bible reader that handles commentaries alongside any bible, like AndBible or xiphos...

So your:
``
`sed -e 's/^\(2.4.*) foo/\1 bar/'  -i 1Cor,usfm
``
 would become for you, if you broke bash into sed files
``
`sed -f 1Cor.sed 1Cor.usfm
``
and then for me
``
1Cor 2:4\t"foo" should be replaced by "bar" because...
``
in my TSV file which get turned into an OSIS commentary XML
sorta like
``
<note type='commentary' osisref='1Cor.2.4'>"foo" should be "bar" because...</note>
``
which I can then use to generate an esword commentary module
that works alongside any Bible that uses KJV versification.

The <because> can handle hrefs and xrefs; so if you look in the files I uploaded, you'll see v=ABCDEFGH which gets turned into a hyperlink to the video of Doug's on youtube.

I have dozens of these TSV files, like over 1000 hyperlinks to all verses mentioned in the website from the verse in the commentary, and over 100 of links from verses to Doug's videos. Plus 2000 KJV translator footnotes which are usually alternate renderings of the Greek, Plus others.

All of this independent of the base bible, or module format (if it can be generated from OSIS - most can).
